phases:
################################################################################
- phase: build_linux_agent
################################################################################
  displayName: Linux Agent
  queue:
    name: Hosted Linux Preview
  condition: eq(false, vagrant)
  steps:

  # Clean
  - checkout: self
    clean: true

  # Build agent layout
  - script: echo build
    workingDirectory: src
    displayName: Build & Layout Release

  # Run test
  - script: echo run
    workingDirectory: src
    displayName: Test

  # Create agent package zip
  - script: echo package
    workingDirectory: src
    displayName: Package Release
    condition: and(succeeded(), ne(variables['build.reason'], 'PullRequest'))

